[project]
name = "test-data-generator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "notebook>=7.5.1",
    "pandas>=2.3.3",
]
